// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UAT.Mobile.Automation.Mobile.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Delivery")]
    public partial class DeliveryFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Delivery.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Delivery", "\tIn order place orders using different delivery options\r\n\tAs a customer\r\n\tI want " +
                    "to place an order using different delivery options available", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("customer delivery selection is displayed on the confirmation page for UK market")]
        [NUnit.Framework.CategoryAttribute("heartbeat")]
        [NUnit.Framework.CategoryAttribute("checkout")]
        [NUnit.Framework.CategoryAttribute("delivery")]
        [NUnit.Framework.CategoryAttribute("uk")]
        [NUnit.Framework.CategoryAttribute("deliveryoption")]
        [NUnit.Framework.TestCaseAttribute("Standard", null)]
        [NUnit.Framework.TestCaseAttribute("Royal Mail", null)]
        [NUnit.Framework.TestCaseAttribute("Express", null)]
        [NUnit.Framework.TestCaseAttribute("Express Noon", null)]
        public virtual void CustomerDeliverySelectionIsDisplayedOnTheConfirmationPageForUKMarket(string deliveryOption, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "heartbeat",
                    "checkout",
                    "delivery",
                    "uk",
                    "deliveryoption"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("customer delivery selection is displayed on the confirmation page for UK market", @__tags);
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
testRunner.Given("I am on the checkout page with a product in my basket", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
testRunner.When(string.Format("I click on a {0} delivery", deliveryOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
testRunner.And("I place an order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
testRunner.Then(string.Format("The confirmation page displays {0} in the delivery selection", deliveryOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("customer delivery selection is displayed on the confirmation page for US market")]
        [NUnit.Framework.CategoryAttribute("heartbeat")]
        [NUnit.Framework.CategoryAttribute("checkout")]
        [NUnit.Framework.CategoryAttribute("delivery")]
        [NUnit.Framework.CategoryAttribute("us")]
        [NUnit.Framework.CategoryAttribute("deliveryoption")]
        [NUnit.Framework.TestCaseAttribute("Standard", null)]
        [NUnit.Framework.TestCaseAttribute("Premium", null)]
        [NUnit.Framework.TestCaseAttribute("Express", null)]
        public virtual void CustomerDeliverySelectionIsDisplayedOnTheConfirmationPageForUSMarket(string deliveryOption, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "heartbeat",
                    "checkout",
                    "delivery",
                    "us",
                    "deliveryoption"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("customer delivery selection is displayed on the confirmation page for US market", @__tags);
#line 22
this.ScenarioSetup(scenarioInfo);
#line 23
testRunner.Given("I am on the checkout page with a product in my basket", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 24
testRunner.When(string.Format("I click on a {0} delivery", deliveryOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 25
testRunner.And("I place an order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
testRunner.Then(string.Format("The confirmation page displays {0} in the delivery selection", deliveryOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("customer delivery selection is displayed on the confirmation page for DE market")]
        [NUnit.Framework.CategoryAttribute("heartbeat")]
        [NUnit.Framework.CategoryAttribute("checkout")]
        [NUnit.Framework.CategoryAttribute("delivery")]
        [NUnit.Framework.CategoryAttribute("de")]
        [NUnit.Framework.CategoryAttribute("deliveryoption")]
        [NUnit.Framework.TestCaseAttribute("Standard", null)]
        [NUnit.Framework.TestCaseAttribute("Express", null)]
        public virtual void CustomerDeliverySelectionIsDisplayedOnTheConfirmationPageForDEMarket(string deliveryOption, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "heartbeat",
                    "checkout",
                    "delivery",
                    "de",
                    "deliveryoption"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("customer delivery selection is displayed on the confirmation page for DE market", @__tags);
#line 35
this.ScenarioSetup(scenarioInfo);
#line 36
testRunner.Given("I am on the checkout page with a product in my basket", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 37
testRunner.When(string.Format("I click on a {0} delivery", deliveryOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
testRunner.And("I place an order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
testRunner.Then(string.Format("The confirmation page displays {0} in the delivery selection", deliveryOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("customer delivery selection is displayed on the confirmation page for FR market")]
        [NUnit.Framework.CategoryAttribute("heartbeat")]
        [NUnit.Framework.CategoryAttribute("checkout")]
        [NUnit.Framework.CategoryAttribute("delivery")]
        [NUnit.Framework.CategoryAttribute("fr")]
        [NUnit.Framework.CategoryAttribute("deliveryoption")]
        [NUnit.Framework.TestCaseAttribute("Standard", null)]
        [NUnit.Framework.TestCaseAttribute("Premium", null)]
        public virtual void CustomerDeliverySelectionIsDisplayedOnTheConfirmationPageForFRMarket(string deliveryOption, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "heartbeat",
                    "checkout",
                    "delivery",
                    "fr",
                    "deliveryoption"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("customer delivery selection is displayed on the confirmation page for FR market", @__tags);
#line 47
this.ScenarioSetup(scenarioInfo);
#line 48
testRunner.Given("I am on the checkout page with a product in my basket", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 49
testRunner.When(string.Format("I click on a {0} delivery", deliveryOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
testRunner.And("I place an order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
testRunner.Then(string.Format("The confirmation page displays {0} in the delivery selection", deliveryOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("customer delivery selection is displayed on the confirmation page for AU market")]
        [NUnit.Framework.CategoryAttribute("heartbeat")]
        [NUnit.Framework.CategoryAttribute("checkout")]
        [NUnit.Framework.CategoryAttribute("delivery")]
        [NUnit.Framework.CategoryAttribute("au")]
        [NUnit.Framework.CategoryAttribute("deliveryoption")]
        [NUnit.Framework.TestCaseAttribute("Standard", null)]
        public virtual void CustomerDeliverySelectionIsDisplayedOnTheConfirmationPageForAUMarket(string deliveryOption, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "heartbeat",
                    "checkout",
                    "delivery",
                    "au",
                    "deliveryoption"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("customer delivery selection is displayed on the confirmation page for AU market", @__tags);
#line 59
this.ScenarioSetup(scenarioInfo);
#line 60
testRunner.Given("I am on the checkout page with a product in my basket", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 61
testRunner.When(string.Format("I click on a {0} delivery", deliveryOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 62
testRunner.And("I place an order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 63
testRunner.Then(string.Format("The confirmation page displays {0} in the delivery selection", deliveryOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("I am able to view a list of locations using click and collect delivery option for" +
            " UK market")]
        [NUnit.Framework.CategoryAttribute("checkout")]
        [NUnit.Framework.CategoryAttribute("delivery")]
        [NUnit.Framework.CategoryAttribute("uk")]
        [NUnit.Framework.TestCaseAttribute("NW10 6NY", null)]
        public virtual void IAmAbleToViewAListOfLocationsUsingClickAndCollectDeliveryOptionForUKMarket(string postcode, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "checkout",
                    "delivery",
                    "uk"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I am able to view a list of locations using click and collect delivery option for" +
                    " UK market", @__tags);
#line 69
this.ScenarioSetup(scenarioInfo);
#line 70
testRunner.Given("I have selected UK click and collect as a delivery method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 71
testRunner.When(string.Format("I enter a {0} postcode", postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 72
testRunner.Then("the pickup locations are displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 73
testRunner.And(string.Format("the {0} is shown on the location result panel", postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("I am able to view a list of locations using click and collect delivery option for" +
            " DE market")]
        [NUnit.Framework.CategoryAttribute("checkout")]
        [NUnit.Framework.CategoryAttribute("delivery")]
        [NUnit.Framework.CategoryAttribute("de")]
        [NUnit.Framework.TestCaseAttribute("13435", null)]
        public virtual void IAmAbleToViewAListOfLocationsUsingClickAndCollectDeliveryOptionForDEMarket(string postcode, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "checkout",
                    "delivery",
                    "de"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I am able to view a list of locations using click and collect delivery option for" +
                    " DE market", @__tags);
#line 79
this.ScenarioSetup(scenarioInfo);
#line 80
testRunner.Given("I have selected DE click and collect as a delivery method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 81
testRunner.When(string.Format("I enter a {0} postcode", postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 82
testRunner.Then("the pickup locations are displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 83
testRunner.And(string.Format("the {0} is shown on the location result panel", postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("I am able to view a list of locations using click and collect delivery option for" +
            " FR market")]
        [NUnit.Framework.CategoryAttribute("checkout")]
        [NUnit.Framework.CategoryAttribute("delivery")]
        [NUnit.Framework.CategoryAttribute("fr")]
        [NUnit.Framework.TestCaseAttribute("75016", null)]
        public virtual void IAmAbleToViewAListOfLocationsUsingClickAndCollectDeliveryOptionForFRMarket(string postcode, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "checkout",
                    "delivery",
                    "fr"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I am able to view a list of locations using click and collect delivery option for" +
                    " FR market", @__tags);
#line 89
this.ScenarioSetup(scenarioInfo);
#line 90
testRunner.Given("I have selected FR click and collect as a delivery method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 91
testRunner.When(string.Format("I enter a {0} postcode", postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 92
testRunner.Then("the pickup locations are displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 93
testRunner.And(string.Format("the {0} is shown on the location result panel", postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("validate the click and collect shows on the collection and delivery option panel " +
            "for UK market")]
        [NUnit.Framework.CategoryAttribute("checkout")]
        [NUnit.Framework.CategoryAttribute("delivery")]
        [NUnit.Framework.CategoryAttribute("uk")]
        [NUnit.Framework.TestCaseAttribute("NW10 6NY", null)]
        public virtual void ValidateTheClickAndCollectShowsOnTheCollectionAndDeliveryOptionPanelForUKMarket(string postcode, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "checkout",
                    "delivery",
                    "uk"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("validate the click and collect shows on the collection and delivery option panel " +
                    "for UK market", @__tags);
#line 99
this.ScenarioSetup(scenarioInfo);
#line 100
testRunner.Given("I have selected UK click and collect as a delivery method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 101
testRunner.When(string.Format("I enter a {0} postcode", postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 102
testRunner.And("I select a location", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 103
testRunner.Then("the location is shown on the delivery options panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 104
testRunner.And("the location is displayed on the collection address panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("validate the click and collect shows on the collection and delivery option panel " +
            "for DE market")]
        [NUnit.Framework.CategoryAttribute("checkout")]
        [NUnit.Framework.CategoryAttribute("delivery")]
        [NUnit.Framework.CategoryAttribute("de")]
        [NUnit.Framework.TestCaseAttribute("13435", null)]
        public virtual void ValidateTheClickAndCollectShowsOnTheCollectionAndDeliveryOptionPanelForDEMarket(string postcode, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "checkout",
                    "delivery",
                    "de"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("validate the click and collect shows on the collection and delivery option panel " +
                    "for DE market", @__tags);
#line 110
this.ScenarioSetup(scenarioInfo);
#line 111
testRunner.Given("I have selected DE click and collect as a delivery method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 112
testRunner.When(string.Format("I enter a {0} postcode", postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 113
testRunner.And("I select a location", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 114
testRunner.Then("the location is shown on the delivery options panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 115
testRunner.And("the location is displayed on the collection address panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("validate the click and collect shows on the collection and delivery option panel " +
            "for FR market")]
        [NUnit.Framework.CategoryAttribute("checkout")]
        [NUnit.Framework.CategoryAttribute("delivery")]
        [NUnit.Framework.CategoryAttribute("fr")]
        [NUnit.Framework.TestCaseAttribute("75016", null)]
        public virtual void ValidateTheClickAndCollectShowsOnTheCollectionAndDeliveryOptionPanelForFRMarket(string postcode, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "checkout",
                    "delivery",
                    "fr"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("validate the click and collect shows on the collection and delivery option panel " +
                    "for FR market", @__tags);
#line 121
this.ScenarioSetup(scenarioInfo);
#line 122
testRunner.Given("I have selected FR click and collect as a delivery method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 123
testRunner.When(string.Format("I enter a {0} postcode", postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 124
testRunner.And("I select a location", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 125
testRunner.Then("the location is shown on the delivery options panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 126
testRunner.And("the location is displayed on the collection address panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Place a Click and Collect order without entering delivery contact number for UK m" +
            "arket")]
        [NUnit.Framework.CategoryAttribute("checkout")]
        [NUnit.Framework.CategoryAttribute("delivery")]
        [NUnit.Framework.CategoryAttribute("uk")]
        [NUnit.Framework.TestCaseAttribute("NW10 6NY", "", null)]
        [NUnit.Framework.TestCaseAttribute("NW10 6NY", "07953234253", null)]
        public virtual void PlaceAClickAndCollectOrderWithoutEnteringDeliveryContactNumberForUKMarket(string postcode, string contactNumber, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "checkout",
                    "delivery",
                    "uk"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Place a Click and Collect order without entering delivery contact number for UK m" +
                    "arket", @__tags);
#line 132
this.ScenarioSetup(scenarioInfo);
#line 133
testRunner.Given("I have selected UK click and collect as a delivery method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 134
testRunner.When(string.Format("I enter a {0} postcode", postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 135
testRunner.And("I select a location", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 136
testRunner.And(string.Format("I continue on address panel and place order with {0} number", contactNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 137
testRunner.Then("The confirmation page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Place a Click and Collect order without entering delivery contact number for DE m" +
            "arket")]
        [NUnit.Framework.CategoryAttribute("checkout")]
        [NUnit.Framework.CategoryAttribute("delivery")]
        [NUnit.Framework.CategoryAttribute("de")]
        [NUnit.Framework.TestCaseAttribute("13435", "07953234253", null)]
        public virtual void PlaceAClickAndCollectOrderWithoutEnteringDeliveryContactNumberForDEMarket(string postcode, string postNumber, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "checkout",
                    "delivery",
                    "de"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Place a Click and Collect order without entering delivery contact number for DE m" +
                    "arket", @__tags);
#line 144
this.ScenarioSetup(scenarioInfo);
#line 145
testRunner.Given("I have selected DE click and collect as a delivery method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 146
testRunner.When(string.Format("I enter a {0} postcode", postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 147
testRunner.And("I select a location", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 148
testRunner.And(string.Format("I continue on address panel and place order with {0} number", postNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 149
testRunner.Then("The confirmation page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Place a Click and Collect order without entering delivery contact number for FR m" +
            "arket")]
        [NUnit.Framework.CategoryAttribute("checkout")]
        [NUnit.Framework.CategoryAttribute("delivery")]
        [NUnit.Framework.CategoryAttribute("fr")]
        [NUnit.Framework.TestCaseAttribute("75016", "07953234253", null)]
        public virtual void PlaceAClickAndCollectOrderWithoutEnteringDeliveryContactNumberForFRMarket(string postcode, string contactNumber, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "checkout",
                    "delivery",
                    "fr"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Place a Click and Collect order without entering delivery contact number for FR m" +
                    "arket", @__tags);
#line 155
this.ScenarioSetup(scenarioInfo);
#line 156
testRunner.Given("I have selected FR click and collect as a delivery method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 157
testRunner.When(string.Format("I enter a {0} postcode", postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 158
testRunner.And("I select a location", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 159
testRunner.And(string.Format("I continue on address panel and place order with {0} number", contactNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 160
testRunner.Then("The confirmation page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
