//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAT.Mobile.Automation.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CountryCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CountryCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UAT.Mobile.Automation.Data.CountryCode", typeof(CountryCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD.
        /// </summary>
        internal static string Andorra {
            get {
                return ResourceManager.GetString("Andorra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AG.
        /// </summary>
        internal static string AntiguaAndBarbuda {
            get {
                return ResourceManager.GetString("AntiguaAndBarbuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AW.
        /// </summary>
        internal static string Aruba {
            get {
                return ResourceManager.GetString("Aruba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AU.
        /// </summary>
        internal static string Australia {
            get {
                return ResourceManager.GetString("Australia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AT.
        /// </summary>
        internal static string Austria {
            get {
                return ResourceManager.GetString("Austria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BS.
        /// </summary>
        internal static string Bahamas {
            get {
                return ResourceManager.GetString("Bahamas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BH.
        /// </summary>
        internal static string Bahrain {
            get {
                return ResourceManager.GetString("Bahrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BB.
        /// </summary>
        internal static string Barbados {
            get {
                return ResourceManager.GetString("Barbados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BE.
        /// </summary>
        internal static string Belgium {
            get {
                return ResourceManager.GetString("Belgium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BM.
        /// </summary>
        internal static string Bermuda {
            get {
                return ResourceManager.GetString("Bermuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1.
        /// </summary>
        internal static string BFPO {
            get {
                return ResourceManager.GetString("BFPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BR.
        /// </summary>
        internal static string Brazil {
            get {
                return ResourceManager.GetString("Brazil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VG.
        /// </summary>
        internal static string BritishVirginIslands {
            get {
                return ResourceManager.GetString("BritishVirginIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BG.
        /// </summary>
        internal static string Bulgaria {
            get {
                return ResourceManager.GetString("Bulgaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA.
        /// </summary>
        internal static string Canada {
            get {
                return ResourceManager.GetString("Canada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC.
        /// </summary>
        internal static string CanaryIslands {
            get {
                return ResourceManager.GetString("CanaryIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KY.
        /// </summary>
        internal static string CaymanIslands {
            get {
                return ResourceManager.GetString("CaymanIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 91.
        /// </summary>
        internal static string ChannelIslands {
            get {
                return ResourceManager.GetString("ChannelIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN.
        /// </summary>
        internal static string China {
            get {
                return ResourceManager.GetString("China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        internal static string Croatia {
            get {
                return ResourceManager.GetString("Croatia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CW.
        /// </summary>
        internal static string Curacao {
            get {
                return ResourceManager.GetString("Curacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CY.
        /// </summary>
        internal static string Cyprus {
            get {
                return ResourceManager.GetString("Cyprus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CZ.
        /// </summary>
        internal static string CzechRepublic {
            get {
                return ResourceManager.GetString("CzechRepublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DK.
        /// </summary>
        internal static string Denmark {
            get {
                return ResourceManager.GetString("Denmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EE.
        /// </summary>
        internal static string Estonia {
            get {
                return ResourceManager.GetString("Estonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK.
        /// </summary>
        internal static string FalklandIslands_Malvinas {
            get {
                return ResourceManager.GetString("FalklandIslands_Malvinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FJ.
        /// </summary>
        internal static string Fiji {
            get {
                return ResourceManager.GetString("Fiji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FI.
        /// </summary>
        internal static string Finland {
            get {
                return ResourceManager.GetString("Finland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FR.
        /// </summary>
        internal static string France {
            get {
                return ResourceManager.GetString("France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DE.
        /// </summary>
        internal static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GI.
        /// </summary>
        internal static string Gibraltar {
            get {
                return ResourceManager.GetString("Gibraltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GR.
        /// </summary>
        internal static string Greece {
            get {
                return ResourceManager.GetString("Greece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HK.
        /// </summary>
        internal static string HongKong {
            get {
                return ResourceManager.GetString("HongKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HU.
        /// </summary>
        internal static string Hungary {
            get {
                return ResourceManager.GetString("Hungary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS.
        /// </summary>
        internal static string Iceland {
            get {
                return ResourceManager.GetString("Iceland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN.
        /// </summary>
        internal static string India {
            get {
                return ResourceManager.GetString("India", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IE.
        /// </summary>
        internal static string Ireland {
            get {
                return ResourceManager.GetString("Ireland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IL.
        /// </summary>
        internal static string Israel {
            get {
                return ResourceManager.GetString("Israel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT.
        /// </summary>
        internal static string Italy {
            get {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JM.
        /// </summary>
        internal static string Jamaica {
            get {
                return ResourceManager.GetString("Jamaica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JP.
        /// </summary>
        internal static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JO.
        /// </summary>
        internal static string Jordan {
            get {
                return ResourceManager.GetString("Jordan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KR.
        /// </summary>
        internal static string KoreaRepublicOf {
            get {
                return ResourceManager.GetString("KoreaRepublicOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KW.
        /// </summary>
        internal static string Kuwait {
            get {
                return ResourceManager.GetString("Kuwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LV.
        /// </summary>
        internal static string Latvia {
            get {
                return ResourceManager.GetString("Latvia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LI.
        /// </summary>
        internal static string Liechtenstein {
            get {
                return ResourceManager.GetString("Liechtenstein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LT.
        /// </summary>
        internal static string Lithuania {
            get {
                return ResourceManager.GetString("Lithuania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LU.
        /// </summary>
        internal static string Luxembourg {
            get {
                return ResourceManager.GetString("Luxembourg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY.
        /// </summary>
        internal static string Malaysia {
            get {
                return ResourceManager.GetString("Malaysia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT.
        /// </summary>
        internal static string Malta {
            get {
                return ResourceManager.GetString("Malta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQ.
        /// </summary>
        internal static string Martinique {
            get {
                return ResourceManager.GetString("Martinique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC.
        /// </summary>
        internal static string Monaco {
            get {
                return ResourceManager.GetString("Monaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL.
        /// </summary>
        internal static string Netherlands {
            get {
                return ResourceManager.GetString("Netherlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NZ.
        /// </summary>
        internal static string NewZealand {
            get {
                return ResourceManager.GetString("NewZealand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string Norway {
            get {
                return ResourceManager.GetString("Norway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OM.
        /// </summary>
        internal static string Oman {
            get {
                return ResourceManager.GetString("Oman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL.
        /// </summary>
        internal static string Poland {
            get {
                return ResourceManager.GetString("Poland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT.
        /// </summary>
        internal static string Portugal {
            get {
                return ResourceManager.GetString("Portugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA.
        /// </summary>
        internal static string Qatar {
            get {
                return ResourceManager.GetString("Qatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RO.
        /// </summary>
        internal static string Romania {
            get {
                return ResourceManager.GetString("Romania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RU.
        /// </summary>
        internal static string RussianFederation {
            get {
                return ResourceManager.GetString("RussianFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BL.
        /// </summary>
        internal static string SaintBarthelemy {
            get {
                return ResourceManager.GetString("SaintBarthelemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA.
        /// </summary>
        internal static string SaudiArabia {
            get {
                return ResourceManager.GetString("SaudiArabia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SG.
        /// </summary>
        internal static string Singapore {
            get {
                return ResourceManager.GetString("Singapore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SX.
        /// </summary>
        internal static string SintMaarten {
            get {
                return ResourceManager.GetString("SintMaarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SK.
        /// </summary>
        internal static string Slovakia {
            get {
                return ResourceManager.GetString("Slovakia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SI.
        /// </summary>
        internal static string Slovenia {
            get {
                return ResourceManager.GetString("Slovenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZA.
        /// </summary>
        internal static string SouthAfrica {
            get {
                return ResourceManager.GetString("SouthAfrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ES.
        /// </summary>
        internal static string Spain {
            get {
                return ResourceManager.GetString("Spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE.
        /// </summary>
        internal static string Sweden {
            get {
                return ResourceManager.GetString("Sweden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH.
        /// </summary>
        internal static string Switzerland {
            get {
                return ResourceManager.GetString("Switzerland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TW.
        /// </summary>
        internal static string TaiwanRepublicOfChina {
            get {
                return ResourceManager.GetString("TaiwanRepublicOfChina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TH.
        /// </summary>
        internal static string Thailand {
            get {
                return ResourceManager.GetString("Thailand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TR.
        /// </summary>
        internal static string Turkey {
            get {
                return ResourceManager.GetString("Turkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AE.
        /// </summary>
        internal static string UnitedArabEmirates {
            get {
                return ResourceManager.GetString("UnitedArabEmirates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string UnitedKingdom {
            get {
                return ResourceManager.GetString("UnitedKingdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US.
        /// </summary>
        internal static string UnitedStates {
            get {
                return ResourceManager.GetString("UnitedStates", resourceCulture);
            }
        }
    }
}
