//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAT.MainSite.Automation.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Cookies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cookies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UAT.MainSite.Automation.Data.Cookies", typeof(Cookies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string GE_ISOPERATED {
            get {
                return ResourceManager.GetString("GE_ISOPERATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %7B%22CUID%22%3A%22ec32dd23-eb5f-4ee1-8205-a8c532f9f10f%22%7D.
        /// </summary>
        internal static string GlobalE_CT_Data {
            get {
                return ResourceManager.GetString("GlobalE_CT_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %7B%22SESID%22%3A471770805%2C%22AllowFullTracking%22%3Atrue%7D.
        /// </summary>
        internal static string GlobalE_CT_Tracked {
            get {
                return ResourceManager.GetString("GlobalE_CT_Tracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %7B%22countryISO%22%3A%22JP%22%2C%22currencyCode%22%3A%22JPY%22%2C%22cultureCode%22%3A%22ja%22%7D.
        /// </summary>
        internal static string GlobalE_Data_1 {
            get {
                return ResourceManager.GetString("GlobalE_Data_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;countryISO&quot;:&quot;JP&quot;,&quot;currencyCode&quot;:&quot;JPY&quot;,&quot;cultureCode&quot;:&quot;ja&quot;}.
        /// </summary>
        internal static string GlobalE_Data_2 {
            get {
                return ResourceManager.GetString("GlobalE_Data_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %7B%22showWelcome%22%3Afalse%7D.
        /// </summary>
        internal static string GlobalE_Welcome_Data {
            get {
                return ResourceManager.GetString("GlobalE_Welcome_Data", resourceCulture);
            }
        }
    }
}
