//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAT.MainSite.Automation.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FRMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FRMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UAT.MainSite.Automation.Data.FRMenu", typeof(FRMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessoires.
        /// </summary>
        internal static string Accessories {
            get {
                return ResourceManager.GetString("Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Babys&apos;.
        /// </summary>
        internal static string AllBabys {
            get {
                return ResourceManager.GetString("AllBabys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Boys&apos;.
        /// </summary>
        internal static string AllBoys {
            get {
                return ResourceManager.GetString("AllBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Girls&apos;.
        /// </summary>
        internal static string AllGirls {
            get {
                return ResourceManager.GetString("AllGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bébé.
        /// </summary>
        internal static string Baby {
            get {
                return ResourceManager.GetString("Baby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Boden Garçon.
        /// </summary>
        internal static string BabyBodenBoys {
            get {
                return ResourceManager.GetString("BabyBodenBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Boden Fille.
        /// </summary>
        internal static string BabyBodenGirls {
            get {
                return ResourceManager.GetString("BabyBodenGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premier Noel De Bebe.
        /// </summary>
        internal static string BabysFirstChristmas {
            get {
                return ResourceManager.GetString("BabysFirstChristmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boden et Cowshed.
        /// </summary>
        internal static string BodenAndCowshed {
            get {
                return ResourceManager.GetString("BodenAndCowshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garçon.
        /// </summary>
        internal static string Boys {
            get {
                return ResourceManager.GetString("Boys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boutique Cachemire.
        /// </summary>
        internal static string CashmereShop {
            get {
                return ResourceManager.GetString("CashmereShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enfant.
        /// </summary>
        internal static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noël.
        /// </summary>
        internal static string Christmas {
            get {
                return ResourceManager.GetString("Christmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenues d’hiver.
        /// </summary>
        internal static string ChristmasDayDressing {
            get {
                return ResourceManager.GetString("ChristmasDayDressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tricots de Noël.
        /// </summary>
        internal static string ChristmasKnits {
            get {
                return ResourceManager.GetString("ChristmasKnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déstockage.
        /// </summary>
        internal static string Clearance {
            get {
                return ResourceManager.GetString("Clearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manteaux &amp; Vestes.
        /// </summary>
        internal static string CoatsAndJackets {
            get {
                return ResourceManager.GetString("CoatsAndJackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DressesCategoryId {
            get {
                return ResourceManager.GetString("DressesCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffrets-cadeaux.
        /// </summary>
        internal static string Gifting {
            get {
                return ResourceManager.GetString("Gifting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadeaux Pour Garçon.
        /// </summary>
        internal static string GiftsForBoys {
            get {
                return ResourceManager.GetString("GiftsForBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadeaux Pour Fille.
        /// </summary>
        internal static string GiftsForGirls {
            get {
                return ResourceManager.GetString("GiftsForGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadeaux Pour Elle.
        /// </summary>
        internal static string GiftsForHer {
            get {
                return ResourceManager.GetString("GiftsForHer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadeaux Pour Lui.
        /// </summary>
        internal static string GiftsForHim {
            get {
                return ResourceManager.GetString("GiftsForHim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadeaux Deco.
        /// </summary>
        internal static string GiftsForHome {
            get {
                return ResourceManager.GetString("GiftsForHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-cartes cadeaux.
        /// </summary>
        internal static string GiftVouchers {
            get {
                return ResourceManager.GetString("GiftVouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girls.
        /// </summary>
        internal static string Girls {
            get {
                return ResourceManager.GetString("Girls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacs à main.
        /// </summary>
        internal static string Handbags {
            get {
                return ResourceManager.GetString("Handbags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour la maison.
        /// </summary>
        internal static string Homeware {
            get {
                return ResourceManager.GetString("Homeware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeans.
        /// </summary>
        internal static string Jeans {
            get {
                return ResourceManager.GetString("Jeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Johnnie b Garçon.
        /// </summary>
        internal static string JohnnieBBoys {
            get {
                return ResourceManager.GetString("JohnnieBBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Johnnie b Fille.
        /// </summary>
        internal static string JohnnieBGirls {
            get {
                return ResourceManager.GetString("JohnnieBGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tricots.
        /// </summary>
        internal static string Knitware {
            get {
                return ResourceManager.GetString("Knitware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leggings.
        /// </summary>
        internal static string Leggings {
            get {
                return ResourceManager.GetString("Leggings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MenMenuId {
            get {
                return ResourceManager.GetString("MenMenuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Boden Garçon.
        /// </summary>
        internal static string MiniBodenBoys {
            get {
                return ResourceManager.GetString("MiniBodenBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Boden Fille.
        /// </summary>
        internal static string MiniBodenGirls {
            get {
                return ResourceManager.GetString("MiniBodenGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau-né.
        /// </summary>
        internal static string Newborn {
            get {
                return ResourceManager.GetString("Newborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveautés.
        /// </summary>
        internal static string NewIn {
            get {
                return ResourceManager.GetString("NewIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemises de nuit/Pyjamas.
        /// </summary>
        internal static string Nightwear {
            get {
                return ResourceManager.GetString("Nightwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyjamas &amp; Sous-vêtements.
        /// </summary>
        internal static string NightwearAndUnderwear {
            get {
                return ResourceManager.GetString("NightwearAndUnderwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenues de fête.
        /// </summary>
        internal static string Partywear {
            get {
                return ResourceManager.GetString("Partywear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petit gabarit.
        /// </summary>
        internal static string PetiteRange {
            get {
                return ResourceManager.GetString("PetiteRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barboteuses.
        /// </summary>
        internal static string RompersAndPlaySets {
            get {
                return ResourceManager.GetString("RompersAndPlaySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En promo.
        /// </summary>
        internal static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemises.
        /// </summary>
        internal static string Shirts {
            get {
                return ResourceManager.GetString("Shirts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemises &amp; Chemisiers.
        /// </summary>
        internal static string ShirtsAndBlouses {
            get {
                return ResourceManager.GetString("ShirtsAndBlouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaussures &amp; Bottes.
        /// </summary>
        internal static string ShoesAndBoots {
            get {
                return ResourceManager.GetString("ShoesAndBoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOPPER PAR GAMME.
        /// </summary>
        internal static string ShopByBrand {
            get {
                return ResourceManager.GetString("ShopByBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorts.
        /// </summary>
        internal static string Shorts {
            get {
                return ResourceManager.GetString("Shorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jupes.
        /// </summary>
        internal static string Skirts {
            get {
                return ResourceManager.GetString("Skirts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        internal static string Sportswear {
            get {
                return ResourceManager.GetString("Sportswear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tricots.
        /// </summary>
        internal static string Sweats {
            get {
                return ResourceManager.GetString("Sweats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweat-shirts &amp; Polaires.
        /// </summary>
        internal static string SweatShirtsAndFleeces {
            get {
                return ResourceManager.GetString("SweatShirtsAndFleeces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maillots de bain.
        /// </summary>
        internal static string Swimwear {
            get {
                return ResourceManager.GetString("Swimwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vos préférés.
        /// </summary>
        internal static string TopRated {
            get {
                return ResourceManager.GetString("TopRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tops &amp; Polos.
        /// </summary>
        internal static string TopsAndPolos {
            get {
                return ResourceManager.GetString("TopsAndPolos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tops &amp; T-Shirts.
        /// </summary>
        internal static string TopsAndTShirts {
            get {
                return ResourceManager.GetString("TopsAndTShirts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pantalons.
        /// </summary>
        internal static string Trousers {
            get {
                return ResourceManager.GetString("Trousers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pentalons &amp; Jeans.
        /// </summary>
        internal static string TrousersAndJeans {
            get {
                return ResourceManager.GetString("TrousersAndJeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuniques &amp; Caftans.
        /// </summary>
        internal static string TunicsAndKaftans {
            get {
                return ResourceManager.GetString("TunicsAndKaftans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous-vêtements.
        /// </summary>
        internal static string Underwear {
            get {
                return ResourceManager.GetString("Underwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout afficher.
        /// </summary>
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WomenMenuId {
            get {
                return ResourceManager.GetString("WomenMenuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chic au Bureau.
        /// </summary>
        internal static string WorkwearRange {
            get {
                return ResourceManager.GetString("WorkwearRange", resourceCulture);
            }
        }
    }
}
