//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAT.MainSite.Automation.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UKCustomer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UKCustomer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UAT.MainSite.Automation.Data.UKCustomer", typeof(UKCustomer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boden House.
        /// </summary>
        internal static string AddressLine1 {
            get {
                return ResourceManager.GetString("AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 114 120 Victoria Road.
        /// </summary>
        internal static string AddressLine2 {
            get {
                return ResourceManager.GetString("AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LONDON.
        /// </summary>
        internal static string AddressLine3 {
            get {
                return ResourceManager.GetString("AddressLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W536830404.
        /// </summary>
        internal static string CSAAccountNumber {
            get {
                return ResourceManager.GetString("CSAAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 chapel street.
        /// </summary>
        internal static string CSACustomerAddressLine1 {
            get {
                return ResourceManager.GetString("CSACustomerAddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addingham.
        /// </summary>
        internal static string CSACustomerAddressLine2 {
            get {
                return ResourceManager.GetString("CSACustomerAddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ILKLEY.
        /// </summary>
        internal static string CSACustomerAddressLine3 {
            get {
                return ResourceManager.GetString("CSACustomerAddressLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pjenks@boden.co.uk.
        /// </summary>
        internal static string CSACustomerEmail {
            get {
                return ResourceManager.GetString("CSACustomerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LS29 0PQ.
        /// </summary>
        internal static string CSACustomerPostcode {
            get {
                return ResourceManager.GetString("CSACustomerPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csawebuser@boden.co.uk.
        /// </summary>
        internal static string CSAEmailAddress {
            get {
                return ResourceManager.GetString("CSAEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paul.
        /// </summary>
        internal static string CSAFirstName {
            get {
                return ResourceManager.GetString("CSAFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jenks.
        /// </summary>
        internal static string CSALastName {
            get {
                return ResourceManager.GetString("CSALastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csawebuser1.
        /// </summary>
        internal static string CSAPasswordStage {
            get {
                return ResourceManager.GetString("CSAPasswordStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string CSAPasswordStagingAWS {
            get {
                return ResourceManager.GetString("CSAPasswordStagingAWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testuser-uk-csa@boden.co.uk.
        /// </summary>
        internal static string CSAstagingAWSUK {
            get {
                return ResourceManager.GetString("CSAstagingAWSUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string DOBDay {
            get {
                return ResourceManager.GetString("DOBDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string DOBMonth {
            get {
                return ResourceManager.GetString("DOBMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1978.
        /// </summary>
        internal static string DOBYear {
            get {
                return ResourceManager.GetString("DOBYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testuser-uk-customer-1order@boden.co.uk.
        /// </summary>
        internal static string EmailAccountCredit {
            get {
                return ResourceManager.GetString("EmailAccountCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changeaddress@boden.co.uk.
        /// </summary>
        internal static string EmailChangeAddress {
            get {
                return ResourceManager.GetString("EmailChangeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testuser-uk-staff@boden.co.uk.
        /// </summary>
        internal static string EmailStaff {
            get {
                return ResourceManager.GetString("EmailStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test order, please cancel.
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation.
        /// </summary>
        internal static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave in porch.
        /// </summary>
        internal static string LeaveInPorch {
            get {
                return ResourceManager.GetString("LeaveInPorch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password1.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string PasswordStaff {
            get {
                return ResourceManager.GetString("PasswordStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02089342344.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW10 6NY.
        /// </summary>
        internal static string Postcode {
            get {
                return ResourceManager.GetString("Postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
