//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAT.Mobile.Automation.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AUMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AUMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UAT.Mobile.Automation.Data.AUMenu", typeof(AUMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accessories.
        /// </summary>
        internal static string Accessories {
            get {
                return ResourceManager.GetString("Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all-babys.
        /// </summary>
        internal static string AllBabys {
            get {
                return ResourceManager.GetString("AllBabys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all-boys.
        /// </summary>
        internal static string AllBoys {
            get {
                return ResourceManager.GetString("AllBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all-girls.
        /// </summary>
        internal static string AllGirls {
            get {
                return ResourceManager.GetString("AllGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-au/baby.
        /// </summary>
        internal static string Baby {
            get {
                return ResourceManager.GetString("Baby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to baby-boden-boys.
        /// </summary>
        internal static string BabyBodenBoys {
            get {
                return ResourceManager.GetString("BabyBodenBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to baby-boden-girls.
        /// </summary>
        internal static string BabyBodenGirls {
            get {
                return ResourceManager.GetString("BabyBodenGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to baby-s-first-christmas.
        /// </summary>
        internal static string BabysFirstChristmas {
            get {
                return ResourceManager.GetString("BabysFirstChristmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blog.
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boden-and-cowshed.
        /// </summary>
        internal static string BodenAndCowshed {
            get {
                return ResourceManager.GetString("BodenAndCowshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-au/boys.
        /// </summary>
        internal static string Boys {
            get {
                return ResourceManager.GetString("Boys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cashmere-shop.
        /// </summary>
        internal static string CashmereShop {
            get {
                return ResourceManager.GetString("CashmereShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to children.
        /// </summary>
        internal static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to christmas.
        /// </summary>
        internal static string Christmas {
            get {
                return ResourceManager.GetString("Christmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to christmas-day-dressing.
        /// </summary>
        internal static string ChristmasDayDressing {
            get {
                return ResourceManager.GetString("ChristmasDayDressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to christmas-knits.
        /// </summary>
        internal static string ChristmasKnits {
            get {
                return ResourceManager.GetString("ChristmasKnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clearance.
        /// </summary>
        internal static string Clearance {
            get {
                return ResourceManager.GetString("Clearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coats-jackets.
        /// </summary>
        internal static string CoatsAndJackets {
            get {
                return ResourceManager.GetString("CoatsAndJackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dresses.
        /// </summary>
        internal static string Dresses {
            get {
                return ResourceManager.GetString("Dresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifting.
        /// </summary>
        internal static string Gifting {
            get {
                return ResourceManager.GetString("Gifting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifts-for-boys.
        /// </summary>
        internal static string GiftsForBoys {
            get {
                return ResourceManager.GetString("GiftsForBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifts-for-girls.
        /// </summary>
        internal static string GiftsForGirls {
            get {
                return ResourceManager.GetString("GiftsForGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifts-for-her.
        /// </summary>
        internal static string GiftsForHer {
            get {
                return ResourceManager.GetString("GiftsForHer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifts-for-him.
        /// </summary>
        internal static string GiftsForHim {
            get {
                return ResourceManager.GetString("GiftsForHim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifts-for-home.
        /// </summary>
        internal static string GiftsForHome {
            get {
                return ResourceManager.GetString("GiftsForHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gift-vouchers.
        /// </summary>
        internal static string GiftVouchers {
            get {
                return ResourceManager.GetString("GiftVouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-au/girls.
        /// </summary>
        internal static string Girls {
            get {
                return ResourceManager.GetString("Girls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to handbags.
        /// </summary>
        internal static string Handbags {
            get {
                return ResourceManager.GetString("Handbags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to homeware.
        /// </summary>
        internal static string Homeware {
            get {
                return ResourceManager.GetString("Homeware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jeans.
        /// </summary>
        internal static string Jeans {
            get {
                return ResourceManager.GetString("Jeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to johnnie-b-boys.
        /// </summary>
        internal static string JohnnieBBoys {
            get {
                return ResourceManager.GetString("JohnnieBBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to johnnie-b-girls.
        /// </summary>
        internal static string JohnnieBGirls {
            get {
                return ResourceManager.GetString("JohnnieBGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to knitware.
        /// </summary>
        internal static string Knitware {
            get {
                return ResourceManager.GetString("Knitware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leggings.
        /// </summary>
        internal static string Leggings {
            get {
                return ResourceManager.GetString("Leggings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-au/men.
        /// </summary>
        internal static string Men {
            get {
                return ResourceManager.GetString("Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mini-boden-boys.
        /// </summary>
        internal static string MiniBodenBoys {
            get {
                return ResourceManager.GetString("MiniBodenBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mini-boden-girls.
        /// </summary>
        internal static string MiniBodenGirls {
            get {
                return ResourceManager.GetString("MiniBodenGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newborn.
        /// </summary>
        internal static string Newborn {
            get {
                return ResourceManager.GetString("Newborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new-in.
        /// </summary>
        internal static string NewIn {
            get {
                return ResourceManager.GetString("NewIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nightWear.
        /// </summary>
        internal static string Nightwear {
            get {
                return ResourceManager.GetString("Nightwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nightwear-underwear.
        /// </summary>
        internal static string NightwearAndUnderwear {
            get {
                return ResourceManager.GetString("NightwearAndUnderwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partywear.
        /// </summary>
        internal static string Partywear {
            get {
                return ResourceManager.GetString("Partywear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to petite-range.
        /// </summary>
        internal static string PetiteRange {
            get {
                return ResourceManager.GetString("PetiteRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rompers-play-sets.
        /// </summary>
        internal static string RompersAndPlaySets {
            get {
                return ResourceManager.GetString("RompersAndPlaySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-au/sale.
        /// </summary>
        internal static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shirts.
        /// </summary>
        internal static string Shirts {
            get {
                return ResourceManager.GetString("Shirts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shirts-blouses.
        /// </summary>
        internal static string ShirtsAndBlouses {
            get {
                return ResourceManager.GetString("ShirtsAndBlouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shoes-boots.
        /// </summary>
        internal static string ShoesAndBoots {
            get {
                return ResourceManager.GetString("ShoesAndBoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shop-by-brand.
        /// </summary>
        internal static string ShopByBrand {
            get {
                return ResourceManager.GetString("ShopByBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shorts.
        /// </summary>
        internal static string Shorts {
            get {
                return ResourceManager.GetString("Shorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skirts.
        /// </summary>
        internal static string Skirts {
            get {
                return ResourceManager.GetString("Skirts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sportswear.
        /// </summary>
        internal static string Sportswear {
            get {
                return ResourceManager.GetString("Sportswear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sweats.
        /// </summary>
        internal static string Sweats {
            get {
                return ResourceManager.GetString("Sweats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sweatshirts-fleeces.
        /// </summary>
        internal static string SweatShirtsAndFleeces {
            get {
                return ResourceManager.GetString("SweatShirtsAndFleeces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swimwear.
        /// </summary>
        internal static string Swimwear {
            get {
                return ResourceManager.GetString("Swimwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top-rated.
        /// </summary>
        internal static string TopRated {
            get {
                return ResourceManager.GetString("TopRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tops-polos.
        /// </summary>
        internal static string TopsAndPolos {
            get {
                return ResourceManager.GetString("TopsAndPolos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tops-t-shirts.
        /// </summary>
        internal static string TopsAndTShirts {
            get {
                return ResourceManager.GetString("TopsAndTShirts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trousers.
        /// </summary>
        internal static string Trousers {
            get {
                return ResourceManager.GetString("Trousers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trousers-jeans.
        /// </summary>
        internal static string TrousersAndJeans {
            get {
                return ResourceManager.GetString("TrousersAndJeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tunics-kaftans.
        /// </summary>
        internal static string TunicsAndKaftans {
            get {
                return ResourceManager.GetString("TunicsAndKaftans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to underwear.
        /// </summary>
        internal static string Underwear {
            get {
                return ResourceManager.GetString("Underwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view-all.
        /// </summary>
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-au/womens.
        /// </summary>
        internal static string Women {
            get {
                return ResourceManager.GetString("Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workwear-range.
        /// </summary>
        internal static string WorkwearRange {
            get {
                return ResourceManager.GetString("WorkwearRange", resourceCulture);
            }
        }
    }
}
