//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAT.Mobile.Automation.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DEMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DEMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UAT.Mobile.Automation.Data.DEMenu", typeof(DEMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accessoires.
        /// </summary>
        internal static string Accessories {
            get {
                return ResourceManager.GetString("Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all-babys.
        /// </summary>
        internal static string AllBabys {
            get {
                return ResourceManager.GetString("AllBabys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all-boys.
        /// </summary>
        internal static string AllBoys {
            get {
                return ResourceManager.GetString("AllBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all-girls.
        /// </summary>
        internal static string AllGirls {
            get {
                return ResourceManager.GetString("AllGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de-de/baby.
        /// </summary>
        internal static string Baby {
            get {
                return ResourceManager.GetString("Baby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to baby-boden-jungen.
        /// </summary>
        internal static string BabyBodenBoys {
            get {
                return ResourceManager.GetString("BabyBodenBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to baby-boden-mädchen.
        /// </summary>
        internal static string BabyBodenGirls {
            get {
                return ResourceManager.GetString("BabyBodenGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to babys-erstes-weihnachtsfest.
        /// </summary>
        internal static string BabysFirstChristmas {
            get {
                return ResourceManager.GetString("BabysFirstChristmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blazer.
        /// </summary>
        internal static string Blazer {
            get {
                return ResourceManager.GetString("Blazer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blog.
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boden-und-cowshed.
        /// </summary>
        internal static string BodenAndCowshed {
            get {
                return ResourceManager.GetString("BodenAndCowshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de-de/jungen.
        /// </summary>
        internal static string Boys {
            get {
                return ResourceManager.GetString("Boys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kaschmir.
        /// </summary>
        internal static string Cashmere {
            get {
                return ResourceManager.GetString("Cashmere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kaschmirshop.
        /// </summary>
        internal static string CashmereShop {
            get {
                return ResourceManager.GetString("CashmereShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kinder.
        /// </summary>
        internal static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weihnachten.
        /// </summary>
        internal static string Christmas {
            get {
                return ResourceManager.GetString("Christmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to winteroutfits.
        /// </summary>
        internal static string ChristmasDayDressing {
            get {
                return ResourceManager.GetString("ChristmasDayDressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to festliche-strickwaren.
        /// </summary>
        internal static string ChristmasKnits {
            get {
                return ResourceManager.GetString("ChristmasKnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reduziert.
        /// </summary>
        internal static string Clearance {
            get {
                return ResourceManager.GetString("Clearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mäntel-jacken.
        /// </summary>
        internal static string CoatsAndJackets {
            get {
                return ResourceManager.GetString("CoatsAndJackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kleider.
        /// </summary>
        internal static string Dresses {
            get {
                return ResourceManager.GetString("Dresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geschenkideen.
        /// </summary>
        internal static string Gifting {
            get {
                return ResourceManager.GetString("Gifting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geschenke.
        /// </summary>
        internal static string GiftsForBoys {
            get {
                return ResourceManager.GetString("GiftsForBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geschenke.
        /// </summary>
        internal static string GiftsForGirls {
            get {
                return ResourceManager.GetString("GiftsForGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geschenke-fuer-sie.
        /// </summary>
        internal static string GiftsForHer {
            get {
                return ResourceManager.GetString("GiftsForHer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geschenke-fuer-Ihn.
        /// </summary>
        internal static string GiftsForHim {
            get {
                return ResourceManager.GetString("GiftsForHim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schoenes-fuer-zuhause.
        /// </summary>
        internal static string GiftsForHome {
            get {
                return ResourceManager.GetString("GiftsForHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gift-vouchers.
        /// </summary>
        internal static string GiftVouchers {
            get {
                return ResourceManager.GetString("GiftVouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de-de/madchen.
        /// </summary>
        internal static string Girls {
            get {
                return ResourceManager.GetString("Girls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to handtaschen.
        /// </summary>
        internal static string Handbags {
            get {
                return ResourceManager.GetString("Handbags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schönes-für-zu-hause.
        /// </summary>
        internal static string Homeware {
            get {
                return ResourceManager.GetString("Homeware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jeans.
        /// </summary>
        internal static string Jeans {
            get {
                return ResourceManager.GetString("Jeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to johnnie-b-jungen.
        /// </summary>
        internal static string JohnnieBBoys {
            get {
                return ResourceManager.GetString("JohnnieBBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to johnnie-b-mädchen.
        /// </summary>
        internal static string JohnnieBGirls {
            get {
                return ResourceManager.GetString("JohnnieBGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to knitware.
        /// </summary>
        internal static string Knitware {
            get {
                return ResourceManager.GetString("Knitware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leggings.
        /// </summary>
        internal static string Leggings {
            get {
                return ResourceManager.GetString("Leggings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de-de/herren.
        /// </summary>
        internal static string Men {
            get {
                return ResourceManager.GetString("Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mini-boden-jungen.
        /// </summary>
        internal static string MiniBodenBoys {
            get {
                return ResourceManager.GetString("MiniBodenBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mini-boden-mädchen.
        /// </summary>
        internal static string MiniBodenGirls {
            get {
                return ResourceManager.GetString("MiniBodenGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neugeborene.
        /// </summary>
        internal static string Newborn {
            get {
                return ResourceManager.GetString("Newborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neuheiten.
        /// </summary>
        internal static string NewIn {
            get {
                return ResourceManager.GetString("NewIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nachtwäsche.
        /// </summary>
        internal static string Nightwear {
            get {
                return ResourceManager.GetString("Nightwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nachtwäsche-unterwäsche.
        /// </summary>
        internal static string NightwearAndUnderwear {
            get {
                return ResourceManager.GetString("NightwearAndUnderwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hosen.
        /// </summary>
        internal static string Pants {
            get {
                return ResourceManager.GetString("Pants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partykleidung.
        /// </summary>
        internal static string Partywear {
            get {
                return ResourceManager.GetString("Partywear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to petite-kollektion.
        /// </summary>
        internal static string PetiteRange {
            get {
                return ResourceManager.GetString("PetiteRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strampler-spielsets.
        /// </summary>
        internal static string RompersAndPlaySets {
            get {
                return ResourceManager.GetString("RompersAndPlaySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sale.
        /// </summary>
        internal static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hemden.
        /// </summary>
        internal static string Shirts {
            get {
                return ResourceManager.GetString("Shirts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hemden-blusen.
        /// </summary>
        internal static string ShirtsAndBlouses {
            get {
                return ResourceManager.GetString("ShirtsAndBlouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schuhe-und-stiefel.
        /// </summary>
        internal static string ShoesAndBoots {
            get {
                return ResourceManager.GetString("ShoesAndBoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kollektion-shoppen.
        /// </summary>
        internal static string ShopByBrand {
            get {
                return ResourceManager.GetString("ShopByBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shorts.
        /// </summary>
        internal static string Shorts {
            get {
                return ResourceManager.GetString("Shorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to röcke.
        /// </summary>
        internal static string Skirts {
            get {
                return ResourceManager.GetString("Skirts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sportmode.
        /// </summary>
        internal static string Sportswear {
            get {
                return ResourceManager.GetString("Sportswear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strickwaren.
        /// </summary>
        internal static string Sweaters {
            get {
                return ResourceManager.GetString("Sweaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strickwaren.
        /// </summary>
        internal static string Sweats {
            get {
                return ResourceManager.GetString("Sweats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sweatshirts-fleeces.
        /// </summary>
        internal static string SweatShirtsAndFleeces {
            get {
                return ResourceManager.GetString("SweatShirtsAndFleeces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bademoden.
        /// </summary>
        internal static string Swimwear {
            get {
                return ResourceManager.GetString("Swimwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top-bewertet.
        /// </summary>
        internal static string TopRated {
            get {
                return ResourceManager.GetString("TopRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tops-polos.
        /// </summary>
        internal static string TopsAndPolos {
            get {
                return ResourceManager.GetString("TopsAndPolos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oberteile-t-shirts.
        /// </summary>
        internal static string TopsAndTShirts {
            get {
                return ResourceManager.GetString("TopsAndTShirts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trousers.
        /// </summary>
        internal static string Trousers {
            get {
                return ResourceManager.GetString("Trousers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hosen-jeans.
        /// </summary>
        internal static string TrousersAndJeans {
            get {
                return ResourceManager.GetString("TrousersAndJeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tuniken-kaftane.
        /// </summary>
        internal static string TunicsAndKaftans {
            get {
                return ResourceManager.GetString("TunicsAndKaftans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unterwäsche.
        /// </summary>
        internal static string Underwear {
            get {
                return ResourceManager.GetString("Underwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alle-ansehen.
        /// </summary>
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de-de/damen.
        /// </summary>
        internal static string Women {
            get {
                return ResourceManager.GetString("Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mit-mode-zum-erfolg.
        /// </summary>
        internal static string WorkwearRange {
            get {
                return ResourceManager.GetString("WorkwearRange", resourceCulture);
            }
        }
    }
}
